modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT"
[[mods]] #mandatory
modId="pipeslide" #mandatory
version="${file.jarVersion}" #mandatory
displayName="PipeSlide" #mandatory
authors="MarbleGateKeeper" #optional
description='''
'''
[[dependencies.pipeslide]] #optional
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.pipeslide]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"
